server:
  port: 10010

spring:
  application:
    name: api-geteway #指定服务名
zuul:
  routes:
    consumer:
      path: /consumer/**
      serviceId: consumer
    user-server: #这里是路由id
      path: /user-server/**
      serviceId: user-server
#      url: http://127.0.0.1:8082

eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000