spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
  application:
    name: user-server


server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #调用getHostName获取实例的hostNmae时，返回ip而不是host名称
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 5 # 服务续约的间隔，默认为30秒