server:
  port: 10086 #端口
spring:
  application:
    name: eureka-server #应用名称

eureka:
  client:
    register-with-eureka: false #是否注册自己的信息到EurekaServer
    fetch-registry: false # 是否拉去其他服务的信息
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  server:
    enable-self-preservation: false # 关闭自我保护模式
    eviction-interval-timer-in-ms: 10000 # 扫描失效服务的间隔